// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoBufDataTemplate.proto

#ifndef PROTOBUF_ProtoBufDataTemplate_2eproto__INCLUDED
#define PROTOBUF_ProtoBufDataTemplate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Owlies {
namespace Core {
namespace ChangeEvents {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ProtoBufDataTemplate_2eproto();
void protobuf_AssignDesc_ProtoBufDataTemplate_2eproto();
void protobuf_ShutdownFile_ProtoBufDataTemplate_2eproto();

class Item;

enum ItemType {
  Hat = 0,
  Cape = 1,
  Weapon = 2,
  Shoe = 3,
  Arm_Armour = 4,
  Leg_Armour = 5,
  Shirt = 6
};
bool ItemType_IsValid(int value);
const ItemType ItemType_MIN = Hat;
const ItemType ItemType_MAX = Shirt;
const int ItemType_ARRAYSIZE = ItemType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ItemType_descriptor();
inline const ::std::string& ItemType_Name(ItemType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ItemType_descriptor(), value);
}
inline bool ItemType_Parse(
    const ::std::string& name, ItemType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ItemType>(
    ItemType_descriptor(), name, value);
}
// ===================================================================

class Item : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Owlies.Core.ChangeEvents.Item) */ {
 public:
  Item();
  virtual ~Item();

  Item(const Item& from);

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Item& default_instance();

  void Swap(Item* other);

  // implements Message ----------------------------------------------

  inline Item* New() const { return New(NULL); }

  Item* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Item* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 price = 2;
  bool has_price() const;
  void clear_price();
  static const int kPriceFieldNumber = 2;
  ::google::protobuf::int32 price() const;
  void set_price(::google::protobuf::int32 value);

  // optional .Owlies.Core.ChangeEvents.ItemType itemType = 3 [default = Hat];
  bool has_itemtype() const;
  void clear_itemtype();
  static const int kItemTypeFieldNumber = 3;
  ::Owlies::Core::ChangeEvents::ItemType itemtype() const;
  void set_itemtype(::Owlies::Core::ChangeEvents::ItemType value);

  // @@protoc_insertion_point(class_scope:Owlies.Core.ChangeEvents.Item)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_price();
  inline void clear_has_price();
  inline void set_has_itemtype();
  inline void clear_has_itemtype();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 price_;
  int itemtype_;
  friend void  protobuf_AddDesc_ProtoBufDataTemplate_2eproto();
  friend void protobuf_AssignDesc_ProtoBufDataTemplate_2eproto();
  friend void protobuf_ShutdownFile_ProtoBufDataTemplate_2eproto();

  void InitAsDefaultInstance();
  static Item* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Item

// required string name = 1;
inline bool Item::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Item::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Item::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Item::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Item::name() const {
  // @@protoc_insertion_point(field_get:Owlies.Core.ChangeEvents.Item.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Item::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Owlies.Core.ChangeEvents.Item.name)
}
inline void Item::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Owlies.Core.ChangeEvents.Item.name)
}
inline void Item::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Owlies.Core.ChangeEvents.Item.name)
}
inline ::std::string* Item::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:Owlies.Core.ChangeEvents.Item.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Item::release_name() {
  // @@protoc_insertion_point(field_release:Owlies.Core.ChangeEvents.Item.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Item::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Owlies.Core.ChangeEvents.Item.name)
}

// required int32 price = 2;
inline bool Item::has_price() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Item::set_has_price() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Item::clear_has_price() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Item::clear_price() {
  price_ = 0;
  clear_has_price();
}
inline ::google::protobuf::int32 Item::price() const {
  // @@protoc_insertion_point(field_get:Owlies.Core.ChangeEvents.Item.price)
  return price_;
}
inline void Item::set_price(::google::protobuf::int32 value) {
  set_has_price();
  price_ = value;
  // @@protoc_insertion_point(field_set:Owlies.Core.ChangeEvents.Item.price)
}

// optional .Owlies.Core.ChangeEvents.ItemType itemType = 3 [default = Hat];
inline bool Item::has_itemtype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Item::set_has_itemtype() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Item::clear_has_itemtype() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Item::clear_itemtype() {
  itemtype_ = 0;
  clear_has_itemtype();
}
inline ::Owlies::Core::ChangeEvents::ItemType Item::itemtype() const {
  // @@protoc_insertion_point(field_get:Owlies.Core.ChangeEvents.Item.itemType)
  return static_cast< ::Owlies::Core::ChangeEvents::ItemType >(itemtype_);
}
inline void Item::set_itemtype(::Owlies::Core::ChangeEvents::ItemType value) {
  assert(::Owlies::Core::ChangeEvents::ItemType_IsValid(value));
  set_has_itemtype();
  itemtype_ = value;
  // @@protoc_insertion_point(field_set:Owlies.Core.ChangeEvents.Item.itemType)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ChangeEvents
}  // namespace Core
}  // namespace Owlies

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Owlies::Core::ChangeEvents::ItemType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Owlies::Core::ChangeEvents::ItemType>() {
  return ::Owlies::Core::ChangeEvents::ItemType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoBufDataTemplate_2eproto__INCLUDED
